// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSEMRcpIcR1vzZg8NVTS3M6SriT35ZtaY',
    appId: '1:879559631749:web:7fe3add7ee9da5ac051aec',
    messagingSenderId: '879559631749',
    projectId: 'db-shree',
    authDomain: 'db-shree.firebaseapp.com',
    storageBucket: 'db-shree.firebasestorage.app',
    measurementId: 'G-91JVS8B8RJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGyh1cbtRRlommQ7iqyGUQQv4-JZ_uByk',
    appId: '1:879559631749:android:894438163f204e52051aec',
    messagingSenderId: '879559631749',
    projectId: 'db-shree',
    storageBucket: 'db-shree.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSEMRcpIcR1vzZg8NVTS3M6SriT35ZtaY',
    appId: '1:879559631749:web:2af69ae33e029ccc051aec',
    messagingSenderId: '879559631749',
    projectId: 'db-shree',
    authDomain: 'db-shree.firebaseapp.com',
    storageBucket: 'db-shree.firebasestorage.app',
    measurementId: 'G-1NLKQHNNXZ',
  );
}
